version: "3.8"
services:
    nginx:
        container_name: nginx_app
        build: ./nginx
        restart: always
        volumes: 
            - ./templates:/etc/nginx/templates
        ports:
            - 80:80
            - 443:443

